init_submodule: &init_submodule
  name: apply_deployment
  command: |
    ls
    git submodule init
    git submodule update
    ls models

version: 2.1
jobs:
  init_submodule:
    machine: true
    steps:
      - checkout
      - add_ssh_keys: # machine user
          fingerprints: "71:49:79:ec:2e:08:3e:b9:c3:e6:79:17:52:b9:68:b5"
      - run: *init_submodule

workflows:
  version: 2
  publish_test:
    jobs:
      - init_submodule