init_submodule: &init_submodule
  name: apply_deployment
  command: |
    rm -f pod.yaml
    sed "s~ARG_CIRCLE_TAG~${CIRCLE_TAG}~; s~ARG_NAMESPACE~${NAMESPACE}~; s~ARG_CORE_HOST~${CORE_HOST}~; " ./pod.template.yaml > pod.yaml
    cat pod.yaml
    kubectl delete -f pod.yaml
    kubectl create -f pod.yaml

version: 2.1
jobs:
  init_submodule:
    machine: true
    steps:
      - checkout
      - run: *init_submodule

workflows:
  version: 2
  publish_test:
    jobs:
      - init_submodule